### ISSUE TITLE
About the course text includes the same two course references

### ISSUE THREAD

**Issue by somascope** [vueschool/vuejs-router#1]
In the last paragraph of the "About the course" copy, you mention two previous courses to refer people to. The same course ("Vue.js Components Fundamentals") is mentioned twice...

"We recommend watching [Vue.js Components Fundamentals](https://vueschool.io/courses/vuejs-components-fundamentals) and [Vue.js Components Fundamentals](https://vueschool.io/courses/vuejs-components-fundamentals) if you’re not already familiar with Vue.js and components."

..and I'm guessing you might have intended for the first course & link to be...

"We recommend watching [Vue.js Fundamentals](https://vueschool.io/courses/vuejs-fundamentals) and [Vue.js Components Fundamentals](https://vueschool.io/courses/vuejs-components-fundamentals) if you’re not already familiar with Vue.js and components."

**Comment by debs-obrien** [comment]
Oh, thanks for that I will make sure Rolf or Alex modify the links. Hope your enjoying the course :)

**Comment by debs-obrien** [comment]
Ahh thanks. That means a lot. Working on my next course now 😃
